clusterGroup:
  name: default
  isHubCluster: true

  scheduler:
    mastersSchedulable: true

  namespaces:
  - echo
  - curl
  - egressip-ipam-operator:
      targetNamespaces: null

  subscriptions:
    egressipam:
      name: egressip-ipam-operator
      channel: alpha
      source: community-operators
      sourceNamespace: openshift-marketplace

  projects:
  - default
  
  applications:
    echo:
      name: echo
      path: charts/echo
      project: default
      namespace: echo
    curl:
      name: curl
      path: charts/curl
      project: default
      namespace: curl
    egressipam:
      name: egressipam
      project: default
      path: charts/egressipam

  nodes:
  - node03.ocp4.gmbros.local:
      labels:
        egressGateway: "true"

vars:
  curl:
    url: http://echo-echo.apps.ocp4.gmbros.local/say/Hola
    sleep: 5
    node: 'node03.ocp4.gmbros.local'
    timeout: 10
  egressipam:
    name: default
    cidr: 10.0.0.0/24
    topologyLabel: egressGatewaay
