clusterGroup:
  name: default
  isHubCluster: true

  scheduler:
    mastersSchedulable: true

  namespaces:
  - echo
  - curl

  subscriptions: {}

  projects:
  - default
  
  applications:
    echo:
      name: echo
      path: charts/echo
      project: default
      namespace: echo
    curl:
      name: curl
      path: charts/curl
      project: default
      namespace: curl

vars:
  curl:
    url: http://echo-echo.apps.ocp4.gmbros.local/say/Hola
    sleep: 5
    node: 'node03.ocp4.gmbros.local'
    timeout: 10
