clusterGroup:
  name: default
  isHubCluster: true

  scheduler:
    mastersSchedulable: true
    
  namespaces:
  - echo

  subscriptions: {}

  projects:
  - default
  
  applications:
    echo:
      name: echo
      path: charts/echo
      project: default
      namespace: echo

